'use client';
import Link from 'next/link';
import {useState} from 'react';
import {ArrowUpRight,ArrowDown,ArrowUp,Menu,GitBranch} from 'lucide-react';
import {Sheet,SheetTrigger,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {github, type Project} from '@/lib/portfolio-data';
import {profile} from '@/lib/profile';
export function Header(){const [open,setOpen]=useState(false);return <header className="site-header"><div className="wrap nav-inner"><Link href="/" className="wordmark" aria-label="Nabil home">nabil<span>.</span></Link><nav className="desktop-nav" aria-label="Main navigation"><Link href="/#about">About</Link><Link href="/#toolkit">Toolkit</Link><Link href="/#work">Selected work</Link><Link href="/#experience">Experience</Link></nav><a className="nav-contact" href="#contact">Let’s connect <ArrowUpRight size={16}/></a><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><button className="mobile-menu" aria-label="Open navigation"><Menu size={23}/></button></SheetTrigger><SheetContent className="mobile-panel"><SheetTitle className="wordmark">nabil<span>.</span></SheetTitle><SheetDescription>Explore my work and the thinking behind it.</SheetDescription><nav aria-label="Mobile navigation">{[['About','/#about'],['Toolkit','/#toolkit'],['Selected work','/#work'],['Experience','/#experience'],['All projects','/projects'],['Let’s connect','#contact']].map(([label,href])=><Link key={label} href={href} onClick={()=>setOpen(false)}>{label}<ArrowUpRight size={20}/></Link>)}</nav></SheetContent></Sheet></div></header>}
export function SectionLabel({number,children}:{number:string;children:React.ReactNode}){return <div className="section-label"><span>{number}</span>{children}</div>}
export function Footer(){return <footer id="contact" className="contact-section"><div className="wrap"><SectionLabel number="06">LET’S CONNECT</SectionLabel><div className="contact-grid"><h2>Good questions.<br/><span>Better together.</span></h2><div><p>Have an interesting problem,<br/>a project idea, or a new perspective?<br/>I’d love to connect.</p><a className="button button-white" href={"mailto:"+profile.email}>Let’s talk by email <ArrowUpRight size={18}/></a><a className="contact-email" href={"mailto:"+profile.email}>{profile.email}</a><div className="contact-links"><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={15}/></a><a href={github} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15}/></a><a href={profile.resume} download={profile.resumeFilename}>Download CV <ArrowDown size={15}/></a></div></div></div><div className="footer-bottom"><p>© 2026 Muhammad Pangeran Nabil</p><span>Built with curiosity. Grounded in evidence.</span><a href="#top">Back to top <ArrowUp size={15}/></a></div></div></footer>}
export function DataField(){return <div className="data-field" aria-label="Abstract data points forming a pattern"><div className="field-label"><span className="tiny-cross">+</span> FROM PATTERNS TO PERSPECTIVE</div><svg viewBox="0 0 560 475" role="img" aria-label="A field of blue points with an emerging signal"><defs><pattern id="grid" width="56" height="56" patternUnits="userSpaceOnUse"><path d="M 56 0 L 0 0 0 56" fill="none" stroke="#9598ff" strokeWidth=".5"/></pattern><radialGradient id="fade"><stop offset="0%" stopColor="#3432a0" stopOpacity="0"/><stop offset="100%" stopColor="#3432a0"/></radialGradient></defs><rect width="560" height="475" fill="url(#grid)"/><ellipse cx="282" cy="230" rx="213" ry="177" fill="none" stroke="#919aff" strokeDasharray="3 7"/><ellipse cx="282" cy="230" rx="154" ry="126" fill="none" stroke="#696bc5"/>{Array.from({length:340},(_,i)=>{const a=i*2.399963;const r=11.5*Math.sqrt(i);const x=282+Math.cos(a)*r;const y=230+Math.sin(a)*r*.77;return <circle key={i} cx={x.toFixed(3)} cy={y.toFixed(3)} r={i%9===0?3:1.8} fill={i%5===0?'#83edff':'#b6bcff'} opacity={.25+(i%6)*.11}/>})}<path className="signal-path" pathLength="1" d="M91 296 C166 310 168 203 239 221 S343 252 395 164 S444 131 470 133" stroke="#7de3ff" strokeWidth="3" fill="none"/><circle className="signal-point" cx="395" cy="164" r="6" fill="#fff" stroke="#9b85ff" strokeWidth="3"/><path d="M399 158 L423 122 L476 122" fill="none" stroke="#9caee1"/><text x="422" y="109" fill="#daedff" fontSize="12" fontFamily="monospace">a useful signal.</text><text x="73" y="412" fill="#8d98ab" fontSize="10" fontFamily="monospace">x</text><text x="487" y="62" fill="#8d98ab" fontSize="10" fontFamily="monospace">y</text></svg><div className="field-bottom"><span>QUESTION → EXPLORE → UNDERSTAND</span><span>FIG. 001</span></div></div>}
export function ProjectVisual({project:p}:{project:Project}){return <div className={'project-visual '+p.color}><div className="visual-heading"><span>{p.number==='01'?'OLIST / ANALYTICAL SNAPSHOT':p.number==='02'?'STUDENT SUCCESS / REVIEW POLICY':'INDOBERT / TEXT TO SIGNAL'}</span><span>{p.number==='01'?'2016—2018':p.number==='02'?'HISTORICAL HOLDOUT':'INDONESIAN NLP'}</span></div>{p.number==='01'?<div className="olist-art"><div className="order-total"><span>96,478</span><p>delivered orders.<br/>One connected picture.</p></div><div className="gmv-bars"><div><span>Product GMV</span><strong>R$13.22M</strong><i style={{width:'85.75%'}}/></div><div><span>Order value, incl. freight</span><strong>R$15.42M</strong><i style={{width:'100%'}}/></div></div></div>:p.number==='02'?<div className="student-art"><div className="recall-ring"><svg viewBox="0 0 180 180" aria-hidden="true"><circle cx="90" cy="90" r="76" fill="none" stroke="#dcd8eb" strokeWidth="8"/><circle cx="90" cy="90" r="76" fill="none" stroke="#7465a9" strokeWidth="8" strokeDasharray="420.36 477.52" transform="rotate(-90 90 90)" strokeLinecap="round"/></svg><div><strong>88.03<span>%</span></strong><small>DROPOUT RECALL</small></div></div><div className="recall-caption"><strong>250 / 284</strong><span>historical cases detected</span><small>THRESHOLD 0.19 · HUMAN REVIEW</small></div></div>:<div className="nlp-art"><div className="tokens"><span>bahasa</span><span>makna</span><span>konteks</span></div><div className="model-line"/><div className="bert-node"><GitBranch size={20}/>IndoBERT<span>language → understanding</span></div><div className="model-line"/><div className="sentiments"><span><i/>Positive</span><span><i/>Neutral</span><span><i/>Negative</span></div></div>}<div className="visual-foot"><span>{p.number==='01'?'Delivered-order baseline · GMV excludes freight':p.number==='02'?'Recall shown with precision and workload in the case study':'Three-class inference · interactive Streamlit application'}</span><span>↗</span></div></div>}
export function ProjectCard({project:p,featured=false}:{project:Project;featured?:boolean}){return <article className={'project-card project-'+p.color+(featured?' featured':'')}><Link href={'/projects/'+p.slug} className="project-image-link" aria-label={'Read '+p.title+' case study'}><ProjectVisual project={p}/><span className="project-open"><ArrowUpRight size={24}/></span></Link><div className="project-card-body"><div className="project-category"><span>{p.category}</span><span>/{p.number}</span></div><Link href={'/projects/'+p.slug}><h3>{p.shortTitle}</h3></Link><p>{p.description}</p><div className="project-meta"><div className="tags">{p.tools.map(t=><span key={t}>{t}</span>)}</div><Link href={'/projects/'+p.slug} className="text-link">Case study <ArrowUpRight size={16}/></Link></div></div></article>}
// Original project figures stay on GitHub; static export does not optimize remote images.
// eslint-disable-next-line @next/next/no-img-element
export function SourceImage({src,alt,source}:{src:string;alt:string;source:string}){const [failed,setFailed]=useState(false);return <figure className="source-figure">{!failed&&<img src={src} alt={alt} loading="lazy" onError={()=>setFailed(true)}/>}<figcaption>{failed?'Explore the original project figures and application in the repository.':alt} <a href={source} target="_blank" rel="noreferrer">View source ↗</a></figcaption></figure>}
export {ArrowUpRight,ArrowDown};
